### ISSUE TITLE
Oauth2 keyclock self-hosted

### ISSUE THREAD

**Issue by oAsis-88** [camunda-community-hub/pyzeebe#384]
### Here is my piece of code:
``` python
ZEEBE_CLIENT_ID = "..."
ZEEBE_CLIENT_SECRET = "..."
ZEEBE_AUTHORIZATION_SERVER_URL = "..."
ZEEBE_AUDIENCE = "..."
ZEEBE_ADDRESS = "..."

data = {
    # "audience": ZEEBE_AUDIENCE,
    "client_id": ZEEBE_CLIENT_ID,
    "client_secret": ZEEBE_CLIENT_SECRET,
    "grant_type": "client_credentials",
}
response = requests.post(
    ZEEBE_AUTHORIZATION_SERVER_URL,
    data=data,
)
token = response.json()["access_token"]
auth_creds = grpc.access_token_call_credentials(token)
ssl_creds = grpc.ssl_channel_credentials()
channel_creds = grpc.composite_channel_credentials(ssl_creds, auth_creds)
secure_channel = grpc.secure_channel(ZEEBE_ADDRESS, channel_creds)
zeebe_client = ZeebeClient(secure_channel)
```
### And i get next Exception:
```
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<main() done, defined at ... exception=<_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "DNS resolution failed for https://x.x.x.x:26500: UNAVAILABLE: WSA Error"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-02-06T19:59:13.3648089+00:00", grpc_status:14, grpc_message:"DNS resolution failed for https://x.x.x.x:26500: UNAVAILABLE: WSA Error"}"
>>
  File "...\.venv\lib\site-packages\grpc\_channel.py", line 1003, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "DNS resolution failed for https://x.x.x.x:26500: UNAVAILABLE: WSA Error"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-02-06T19:59:13.3648089+00:00", grpc_status:14, grpc_message:"DNS resolution failed for https://x.x.x.x:26500: UNAVAILABLE: WSA Error"}"
>
```
### So I have two questions:
**1) Is there any appropriate method to connect to self-hosted zeebe with pyzeebe and token?
2) What am I doing wrong?**

**Comment by phoekoby** [comment]
It's looks like working with exceptions???????
```
import asyncio
import collections

import grpc
import requests
from pyzeebe import ZeebeClient

ZEEBE_AUTHENTICATION_MODE = ""
ZEEBE_CLIENT_ID = ""
ZEEBE_CLIENT_SECRET = ""
RESOURCE_AUTHORIZATIONS_ENABLED = ""
ZEEBE_AUTHORIZATION_SERVER_URL = ""

ZEEBE_ADDRESS = ''

data = {
    "grant_type": "client_credentials",
    "client_id": ZEEBE_CLIENT_ID,
    "client_secret": ZEEBE_CLIENT_SECRET
}
response = requests.post(
    ZEEBE_AUTHORIZATION_SERVER_URL,
    data=data
)
token = response.json()["access_token"]

auth_creds = grpc.access_token_call_credentials(token)


class _ClientCallDetails(
    collections.namedtuple(
        "_ClientCallDetails", ("method", "timeout", "metadata", "credentials")
    ),
    grpc.ClientCallDetails,
):
    pass


class MetadataClientInterceptor(
    grpc.UnaryUnaryClientInterceptor,

):
    def __init__(self, key, value):
        self._key = key
        self._value = value

    def _add_metadata(self, client_call_details):
        if client_call_details.metadata is not None:
            client_call_details.metadata.append((self._key, self._value))
        else:
            metadata = list()
            metadata.append(
                (
                    self._key,
                    self._value,
                )
            )
            client_call_details = _ClientCallDetails(
                client_call_details.method,
                client_call_details.timeout,
                metadata,
                client_call_details.credentials,
            )

        return client_call_details

    def intercept_unary_unary(self, continuation, client_call_details, request):
        client_call_details = self._add_metadata(client_call_details)
        response = continuation(client_call_details, request)
        return response


secure_channel = grpc.insecure_channel(ZEEBE_ADDRESS)

interceptor = MetadataClientInterceptor("authorization", "Bearer " + token)

insecure_channel = grpc.intercept_channel(secure_channel, interceptor)

zeebe_client = ZeebeClient(insecure_channel)

asyncio.run(zeebe_client.cancel_process_instance(process_instance_key=1234))

```

**Comment by phoekoby** [comment]
But I got exception:
```
Traceback (most recent call last):
  File "...\zeebe_test.py", line 81, in <module>
    asyncio.run(zeebe_client.cancel_process_instance(process_instance_key=1234))
  File "C:\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\pyzeebe\client\client.py", line 104, in cancel_process_instance
    await self.zeebe_adapter.cancel_process_instance(process_instance_key=process_instance_key)
  File "...\venv\Lib\site-packages\pyzeebe\grpc_internals\zeebe_process_adapter.py", line 74, in cancel_process_instance
    await self._gateway_stub.CancelProcessInstance(
TypeError: object CancelProcessInstanceResponse can't be used in 'await' expression

Process finished with exit code 1

```
